# https://docs.travis-ci.com/user/reference/overview/#linux
dist: bionic

language: php

cache:
  directories:
    - "$HOME/.composer/cache"

php:
  # giacocorsiglia/stubs-generator does not support PHP 7.0
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"

before_install:
  - |
    phpenv config-rm xdebug.ini
  - |
    composer validate --strict

install:
  - |
    if ! php --ri sodium; then
      # https://github.com/paragonie/sodium_compat/pull/104
      #composer require --no-interaction --dev "paragonie/sodium_compat"
      LIBSODIUM_VERSION="1.0.18"
      wget "https://github.com/jedisct1/libsodium/releases/download/${LIBSODIUM_VERSION}-RELEASE/libsodium-${LIBSODIUM_VERSION}.tar.gz"
      tar -xf libsodium-${LIBSODIUM_VERSION}.tar.gz
      cd libsodium-${LIBSODIUM_VERSION} && ./configure --prefix="$HOME/libsodium" && make check && make install && cd -
      LD_LIBRARY_PATH="$HOME/libsodium/lib:$LD_LIBRARY_PATH" \
        PKG_CONFIG_PATH="$HOME/libsodium/lib/pkgconfig:$PKG_CONFIG_PATH" \
        LDFLAGS="-L$HOME/libsodium/lib" \
        pecl install libsodium
      php --ri sodium
    fi
  - |
    composer install --no-interaction --no-suggest
  - |
    composer run-script post-install-cmd

before_script:
  - |
    cat ./source/wordpress/wp-includes/version.php
    if [ "$(phpenv version-name)" == 7.4 ]; then
        # Hide deprecated errors
        sed -e '3s/^/error_reporting(E_ALL ^ E_DEPRECATED);/' -i ./vendor/giacocorsiglia/stubs-generator/bin/generate-stubs
    fi

script:
  - |
    bash -x ./generate.sh
  - |
    php -l wordpress-stubs.php
  - |
    git diff --exit-code
  - |
    php -f wordpress-stubs.php
